/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.proyectovehiculos;

/**
 *
 * @author iehr
 */
public class VehiculosJFrame extends javax.swing.JFrame {

    /**
     * Creates new form VehiculosJFrame
     */
    public VehiculosJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        ButtonReset = new javax.swing.JButton();
        TextFieldMarca = new javax.swing.JTextField();
        TextFieldModelo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        CheckBoxTurismo = new javax.swing.JCheckBox();
        CheckBoxMoto = new javax.swing.JCheckBox();
        CheckBoxCamion = new javax.swing.JCheckBox();
        CheckBoxDescapotao = new javax.swing.JCheckBox();
        CheckBoxSidecar = new javax.swing.JCheckBox();
        CheckBoxRemolque = new javax.swing.JCheckBox();
        ButtonEnviar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 204, 204));

        jLabel1.setText("Alquiler de vehículos");

        ButtonReset.setForeground(new java.awt.Color(204, 0, 51));
        ButtonReset.setText("Resetear");
        ButtonReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonResetActionPerformed(evt);
            }
        });

        TextFieldMarca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextFieldMarcaActionPerformed(evt);
            }
        });

        TextFieldModelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextFieldModeloActionPerformed(evt);
            }
        });

        jLabel2.setText("Marca");

        jLabel3.setText("Modelo");

        jLabel4.setText("Tipo de vehículo");

        jLabel5.setText("Extras:");

        CheckBoxTurismo.setText("Turismo");
        CheckBoxTurismo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckBoxTurismoActionPerformed(evt);
            }
        });

        CheckBoxMoto.setText("Moto");
        CheckBoxMoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckBoxMotoActionPerformed(evt);
            }
        });

        CheckBoxCamion.setText("Camión");
        CheckBoxCamion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckBoxCamionActionPerformed(evt);
            }
        });

        CheckBoxDescapotao.setText("Descapotao");
        CheckBoxDescapotao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckBoxDescapotaoActionPerformed(evt);
            }
        });

        CheckBoxSidecar.setText("Sidecar");

        CheckBoxRemolque.setText("Remolque");

        ButtonEnviar.setForeground(new java.awt.Color(51, 153, 0));
        ButtonEnviar.setText("Enviar");
        ButtonEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonEnviarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(TextFieldModelo, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TextFieldMarca))
                .addGap(128, 128, 128))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(126, 126, 126)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CheckBoxTurismo)
                            .addComponent(CheckBoxCamion)
                            .addComponent(CheckBoxMoto)
                            .addComponent(jLabel4))
                        .addGap(68, 68, 68)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(CheckBoxDescapotao)
                            .addComponent(CheckBoxSidecar)
                            .addComponent(CheckBoxRemolque)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(ButtonReset)
                        .addGap(18, 18, 18)
                        .addComponent(ButtonEnviar)
                        .addGap(47, 47, 47)))
                .addContainerGap(53, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextFieldMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(TextFieldModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CheckBoxTurismo)
                    .addComponent(CheckBoxDescapotao))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CheckBoxSidecar)
                    .addComponent(CheckBoxMoto))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CheckBoxRemolque)
                    .addComponent(CheckBoxCamion))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButtonReset)
                    .addComponent(ButtonEnviar))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
 
    
    private void TextFieldModeloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextFieldModeloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextFieldModeloActionPerformed

    private void CheckBoxMotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckBoxMotoActionPerformed
        if (CheckBoxMoto.isSelected()){
            CheckBoxTurismo.setSelected(false);
            CheckBoxCamion.setSelected(false);
            CheckBoxDescapotao.setSelected(false);
            CheckBoxRemolque.setSelected(false);
            CheckBoxDescapotao.setEnabled(false);
            CheckBoxRemolque.setEnabled(false);
            CheckBoxSidecar.setEnabled(true);
        }
        
    }//GEN-LAST:event_CheckBoxMotoActionPerformed

    private void CheckBoxDescapotaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckBoxDescapotaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CheckBoxDescapotaoActionPerformed

    private void ButtonEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonEnviarActionPerformed
        String marca = "";
        String modelo = "";
        marca = TextFieldMarca.getText();
        modelo = TextFieldModelo.getText();
        System.out.print("Has seleccionado un/una " +marca+ " " +modelo);
        if (CheckBoxSidecar.isSelected()){
            System.out.print(" con sidecar");
        }
        if (CheckBoxDescapotao.isSelected()){
            System.out.print(" descapotao");
        }
        if (CheckBoxRemolque.isSelected()){
            System.out.print(" con remolque");
        }
    }//GEN-LAST:event_ButtonEnviarActionPerformed

    private void CheckBoxTurismoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckBoxTurismoActionPerformed
        if (CheckBoxTurismo.isSelected()){
            CheckBoxMoto.setSelected(false);
            CheckBoxCamion.setSelected(false);
            CheckBoxSidecar.setSelected(false);
            CheckBoxDescapotao.setEnabled(true);
            CheckBoxRemolque.setEnabled(true);
            CheckBoxSidecar.setEnabled(false);
        }
    }//GEN-LAST:event_CheckBoxTurismoActionPerformed

    private void CheckBoxCamionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckBoxCamionActionPerformed
        if (CheckBoxCamion.isSelected()){
            CheckBoxMoto.setSelected(false);
            CheckBoxTurismo.setSelected(false);
            CheckBoxSidecar.setSelected(false);
            CheckBoxDescapotao.setSelected(false);
            CheckBoxDescapotao.setEnabled(false);
            CheckBoxRemolque.setEnabled(true);
            CheckBoxSidecar.setEnabled(false);
        }
    }//GEN-LAST:event_CheckBoxCamionActionPerformed

    private void ButtonResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonResetActionPerformed
            CheckBoxMoto.setSelected(false);
            CheckBoxTurismo.setSelected(false);
            CheckBoxCamion.setSelected(false);
            CheckBoxSidecar.setSelected(false);
            CheckBoxDescapotao.setSelected(false);
            CheckBoxSidecar.setSelected(false);
            CheckBoxDescapotao.setEnabled(true);
            CheckBoxRemolque.setEnabled(true);
            CheckBoxSidecar.setEnabled(true);
            CheckBoxMoto.setEnabled(true);
            CheckBoxTurismo.setEnabled(true);
            CheckBoxCamion.setEnabled(true);
            TextFieldMarca.setText("");
            TextFieldModelo.setText("");
    }//GEN-LAST:event_ButtonResetActionPerformed

    private void TextFieldMarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextFieldMarcaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextFieldMarcaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VehiculosJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VehiculosJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VehiculosJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VehiculosJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VehiculosJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonEnviar;
    private javax.swing.JButton ButtonReset;
    private javax.swing.JCheckBox CheckBoxCamion;
    private javax.swing.JCheckBox CheckBoxDescapotao;
    private javax.swing.JCheckBox CheckBoxMoto;
    private javax.swing.JCheckBox CheckBoxRemolque;
    private javax.swing.JCheckBox CheckBoxSidecar;
    private javax.swing.JCheckBox CheckBoxTurismo;
    private javax.swing.JTextField TextFieldMarca;
    private javax.swing.JTextField TextFieldModelo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
