#include <stdio.h>
#include <math.h>
#include <stdlib.h>
#include <time.h>
#include <unistd.h>
#define MIN_RESULT 1
#define MAX_RESULT 100

int main (){
    pid_t id;
    id = fork();
    int random_number;
    int random_number2;
     if (id != 0) {
        // Set a seed based on the parent process's PID
        srand(getpid());
        random_number = rand();
        printf("Random number (Parent - PID %d): %d\n", (int)getpid(), random_number);
        int random_range = (rand() % (MAX_RESULT - MIN_RESULT + 1)) + MIN_RESULT;
        printf("Random number generated by PARENT in the range [%d, %d]: %d\n", MIN_RESULT, MAX_RESULT, random_range);
    } else {
        // Set a seed based on the child process's PID
        srand(getpid());
        random_number = rand();
        printf("Random number (Child - PID %d): %d\n", (int)getpid(), random_number);
        int random_range = (rand() % (MAX_RESULT - MIN_RESULT + 1)) + MIN_RESULT;
        printf("Random number generated by CHILD in the range [%d, %d]: %d\n", MIN_RESULT, MAX_RESULT, random_range);
    }
    

}