#include <stdio.h>
#include <math.h>
#include <stdlib.h>
#include <time.h>
#include <unistd.h>
#include <sys/wait.h>
#define MIN_RESULT 1
#define MAX_RESULT 100
#define N_RANDOMS 3

int main (){
    pid_t id;
    int random_number;
    int fd[2];
    pipe(fd);
    id = fork();



    if (id != 0) {
        // Set a seed based on the parent process's PID
        srand(getpid());
        close(fd[0]);

        // 
        for (int i = 0; i < N_RANDOMS; i++) {
            random_number = rand();
            int random_range = (rand() % (MAX_RESULT - MIN_RESULT + 1)) + MIN_RESULT;
            printf("Random number generated by PARENT in the range [%d, %d]: %d\n", MIN_RESULT, MAX_RESULT, random_range);
            write(fd[1], &random_number, sizeof(int));
        }

        close(fd[1]);


    } else {
        close(fd[1]);
        wait(NULL);
        sleep(3);

        printf("Im the child, Ive received these numbers : \n");

        for (int i = 0; i < N_RANDOMS ; i++)
        {
            
            read(fd[0], &random_number, sizeof(int));
            printf("%d \n", random_number);

        }
        
        close(fd[0]);

    }
    

}